### PR TITLE
Bootstrap integration

### PR DESCRIPTION
**Pull request by tboerger**
This pull request handles the bootstrap integration for the barclamp. **It depends on https://github.com/crowbar/barclamp-crowbar/pull/790**

### CODE REVIEW

**Comment by dpaterson** [comment]
Don't think RAID and BIOS can be touched,  see Arkady's state of roxy email on the crowbar list:
"b. Barclamp_dell_raid and barclamp_dell_bios – any changes to these MUST be reviewed and approved by Dell. First, the current repos for them are shared for multiple releases: roxy, hadoop-2.4 and hydrogen. Thus, any change impacts all three. Second in order to test it actual HW testing is required and only Dell folks know how to test changes in these barclamps. It is best not to touch these by anybody but Dell folks."

**Comment by arkadykanevsky** [comment]
-1 this change will break other branches that use this repo.

**Comment by tboerger** [comment]
But it only touches the roxy branch to get the bootstrap branding here too?

**Comment by vuntz** [comment]
I'm confused because strings seem to be duplicated in two files: crowbar.yml and the config/locales/ one. Shouldn't this be fixed?

**Comment by tboerger** [comment]
@vuntz For this branch I left it like it was. For the locales pull request I fixed that.

**Pull request merged**
